### PR TITLE
Fix #7, make number picker work

### LINKED ISSUE #7: [Order] Complete number / amount picker
Current picker doesn't work. Order view should have a workable number / amount picker.

### PR DESCRIPTION
**Pull request by kuoe0**
1. add option field
2. make amount button work

### CODE REVIEW

File: src/js/components/order.js [hunk 1]
```diff
@@ -10,6 +11,53 @@ import PanelGroup from 'react-bootstrap/lib/PanelGroup';
 import Row from 'react-bootstrap/lib/Row';
 import Table from 'react-bootstrap/lib/Table';
 
+class AmountField extends React.Component {
```
Comment (rickychien) [inline src/js/components/order.js]: Extract this component out of Order is exactly right.
We could do more to rename it to `NumberInput`, and separate it to another file in terms of reusing NumberInput somewhere.

File: src/js/components/order.js [hunk 2]
```diff
@@ -10,6 +11,53 @@ import PanelGroup from 'react-bootstrap/lib/PanelGroup';
...
+  constructor(props) {
+    super(props);
+
+    this.state = {
+      value: this.props.value != null ? parseInt(this.props.value) : 0
```
Comment (rickychien) [inline src/js/components/order.js]: replace `null` with `undefined`
If someone doesn't pass props.value it will return `undefined` that isn't equal to `null`.

File: src/js/components/order.js [hunk 3]
```diff
@@ -10,6 +11,53 @@ import PanelGroup from 'react-bootstrap/lib/PanelGroup';
...
+    }
+
+    this.increase = this._increase.bind(this);
+    this.decrease = this._decrease.bind(this);
+    this.update = this._update.bind(this);
+  }
+
+  _increase() {
+    this.setState({value: this.state.value + 1});
```
Comment (rickychien) [inline src/js/components/order.js]: nit: coding style

``` js
this.setState({
  value: this.state.value + 1
});
```

File: src/js/components/order.js [hunk 4]
```diff
@@ -10,6 +11,53 @@ import PanelGroup from 'react-bootstrap/lib/PanelGroup';
...
+  }
+
+  _decrease() {
+    this.setState({value: this.state.value > 0 ? this.state.value - 1 : 0});
```
Comment (rickychien) [inline src/js/components/order.js]: nit: coding style as above

File: src/js/components/order.js [hunk 5]
```diff
@@ -10,6 +11,53 @@ import PanelGroup from 'react-bootstrap/lib/PanelGroup';
...
+  }
+
+  _update(evt) {
+    let val = evt.target.value;
+    this.setState({value: val == "" ? 0 : parseInt(val)});
```
Comment (rickychien) [inline src/js/components/order.js]: nit: coding style as above

File: src/css/main.css [hunk 6]
```diff
@@ -1,61 +1,12 @@
-@import url(http://fonts.googleapis.com/css?family=Roboto:400,300,500);
```
Comment (rickychien) [inline src/css/main.css]: nit: remove newline

File: src/js/components/order.js [hunk 7]
```diff
@@ -10,6 +11,55 @@ import PanelGroup from 'react-bootstrap/lib/PanelGroup';
...
+
+  render() {
+    let minusBtn = <Button onClick={this.decrease}><Glyphicon glyph="minus" /></Button>;
+    let plusBtn = <Button onClick={this.increase}><Glyphicon glyph="plus" /></Button>;
+
+    return (
+      <Input
+        type='number'
+        bsSize='small'
+        style={{ textAlign: 'center' }}
```
Comment (rickychien) [inline src/js/components/order.js]: nit: remove whitespaces

``` js
style={{textAlign: 'center'}}
```

File: src/js/components/order.js [hunk 8]
```diff
@@ -10,6 +11,55 @@ import PanelGroup from 'react-bootstrap/lib/PanelGroup';
...
+  constructor(props) {
+    super(props);
+
+    this.state = {
+      value: this.props.value != undefined ? parseInt(this.props.value) : 0
+    }
+
+    this.increase = this._increase.bind(this);
+    this.decrease = this._decrease.bind(this);
+    this.update = this._update.bind(this);
```
Comment (rickychien) [inline src/js/components/order.js]: private method convention: underline prefix method to tell people don't use it outside of this component

``` js
this._increase = this._increase.bind(this);
this._decrease = this._decrease.bind(this);
this._update = this._update.bind(this);
```
